### ISSUE TITLE
NullPointerException at AbstractMethodFragment.processThrowStatement()

### ISSUE THREAD

**Issue by vipul1994** [tsantalis/JDeodorant#10]
LINKS:
(https://github.com/facebook/facebook-java-ads-sdk.git)

The plugin in eclipse gives entity placement score 0.0
while the commandline throws the following error in log file

(http://pastebin.com/rdHjBMGM)

Kindly tell how to solve the issue.

Will add more projects with same issue.

**Comment by tsantalis** [comment]
I was not able to replicate the Exception for the project you provided.
Are you sure facebook-java-ads-sdk is the right project?

**Comment by vipul1994** [comment]
https://github.com/adamdubiel/jason.git
https://github.com/chewiebug/GCViewer.git
https://github.com/opentripplanner/OpenTripPlanner.git

How about on this. My project stucks after entering into the MoveMethodRefactoring method.

**Comment by vipul1994** [comment]
Can you please check if you are able to run on the following project.

http://10.224.192.192/git/ssep_batch.git
http://10.224.192.192/git/ssep_webapp.git
http://10.224.192.192/git/ssep_webservices.git
http://10.224.192.192/git/transaction-research.git

**Comment by tsantalis** [comment]
Bug replicated in project https://github.com/adamdubiel/jason.git

Method invocation
`toJson(org.jasonjson.core.TypeAdapter<double[]>, double[]):java.lang.String`
cannot be matched with method declaration
`private static <T> String toJson(org.jasonjson.core.TypeAdapter<T> typeAdapter, T value)`
in class org.jasonjson.core.functional.StreamingTypeAdaptersTest

**Comment by tsantalis** [comment]
Fixed in commit [0717332c6be14390babaaf5865c2548e35117ba5](https://github.com/tsantalis/JDeodorant/commit/0717332c6be14390babaaf5865c2548e35117ba5)

**Comment by tsantalis** [comment]
Bug replicated in project [https://github.com/chewiebug/GCViewer.git](https://github.com/chewiebug/GCViewer.git)

Creating the FeatureEnvyVisualizationData for method
`private DataReader getDataReaderBySample(String s, GCResource gcResource, InputStream in)`
in class com.tagtraum.perf.gcviewer.imp.DataReaderFactory
causes java.lang.OutOfMemoryError: Java heap space
because the Lists and Maps retrieved from methodToBeMoved and delegateMethod are not shallow copied.

**Comment by tsantalis** [comment]
Fixed in commit [e76449effbcbf41bbfa5f0fe8cba9ae121fcd6c4](https://github.com/tsantalis/JDeodorant/commit/e76449effbcbf41bbfa5f0fe8cba9ae121fcd6c4)

**Comment by tsantalis** [comment]
Project [https://github.com/opentripplanner/OpenTripPlanner.git](https://github.com/opentripplanner/OpenTripPlanner.git) has no problems
