### ISSUE TITLE
PROBLEM WHILE RUNNING HEADLESS ON MAC OS

### ISSUE THREAD

**Issue by vipul1994** [tsantalis/JDeodorant#11]
I have been working on your plugin for quite a long time for feature envy and been trying to run it headless. 
Though the eclipse.commandline project is working fine on Windows OS and Ubuntu OS it is giving compilation error detected exception on the same set of projects.

`try {
            if(ASTReader.getSystemObject() != null && project.equals(ASTReader.getExaminedProject())) {
                new ASTReader(project, ASTReader.getSystemObject(), null);
            }
            else {
                new ASTReader(project, null);
            }
        }
        catch(CompilationErrorDetectedException e) {
            e.printStackTrace();
        }`

This is the part of code in Standalone file of your project and it is coming in the catch block for every set of projects run on MacOS.

Kindly help with the problem.

**Comment by tsantalis** [comment]
Unable to replicate
