### ISSUE TITLE
Is there a way to run JDeodrant through Commandline? "help wanted"

### ISSUE THREAD

**Issue by shivshnkr** [tsantalis/JDeodorant#2]
I have been going through the codebase, and could not find a way that could help me just identify the code smell by running it through the command-line for my repos without importing them to eclipse. I found the Standalone.java class but it still requires my project to be in workspace. Is there a workaround for this? Thanks in advance.

**Comment by tsantalis** [comment]
JDeodorant depends on Eclipse JDT for AST parsing and binding resolution.
As a result, the analyzed project has to be in a workspace.
We have developed a separate headless plug-in that can programmatically convert your projects into Eclipse projects and run JDeodorant without opening Eclipse.
You can find more details in the following link:
http://users.encs.concordia.ca/~nikolaos/jdeodorant/index.php?option=com_content&view=article&id=87:how-can-i-execute-jdeodorant-in-headless-mode&catid=27:installation-questions&Itemid=41

**Comment by shivshnkr** [comment]
I tried with the headless plugin several times and getting errors: 

<code>!ENTRY org.eclipse.osgi 2 0 2015-09-06 12:12:01.222</code>
<code>!MESSAGE eclipse.commandline.Application cannot be found by eclipse.commandline_1.0.0.201509061201</code>
<code>!STACK 0</code>
<code>java.lang.ClassNotFoundException: eclipse.commandline.Application cannot be found by eclipse.commandline_1.0.0.201509061201</code>
<code>Stacktrace...</code>

<code>!ENTRY org.eclipse.osgi 4 0 2015-09-06 12:12:01.251</code>
<code>!MESSAGE Application error </code>
<code>!STACK 1</code>
<code>org.eclipse.core.runtime.CoreException: Plug-in eclipse.commandline was unable to load class eclipse.commandline.Application.</code>
<code>Stacktrace...</code>

Running on MacOS, with Eclipse Mars version 4.5. Please help

**Comment by tsantalis** [comment]
What happens when you run the headless plug-in from within Eclipse?
(i.e., when you click on Run after step 8 of the guide, before making the command line version)
I have tested the headless plug-in on Windows and Linux, but not MacOS

**Comment by shivshnkr** [comment]
After the step 8, I tried with the next four steps of exporting the jar, and executing the plugin. It gives a bunch of lines as errors of ClassNotFound. I have never developed an eclipse plugin and hence unable to debug. 

http://pastebin.com/LmHXUhK2

I went through the code as well to grab the essential piece which I need. May I know what part of code detects smells? Say I want to detect FeatureEnvy in a folder/set of files, then which classes in codebase should I go through? Thanks for your precious time.

**Comment by shivshnkr** [comment]
When running from eclipse, I get lots of stacktraces, again. 
http://pastebin.com/zM3Z1xMn

**Comment by tsantalis** [comment]
From the stacktrace it looks that you are missing many resource bundles in your configuration.
Please go to the Plug-ins tab of the Lauch configuration (step 7 of the tutorial) and select
Launch with: "all workspace and enabled target plug-ins"
If everything goes well after this change, you should see some output printed in the console by JDeodorant for the projects that are open in the workspace you specified in the Main tab.

**Comment by vipul1994** [comment]
Getting this error on Running The Jdeodorant in headless mode on Windows system.

http://pastebin.com/WFCrKkHR

Running on Eclipse.Mars with jre 1.8
