### ISSUE TITLE
NPE-(Apache Roller)

### ISSUE THREAD

**Issue by feroozkhanchintu** [tsantalis/JDeodorant#54]
Null Pointer Exception in 
Path - roller-master\app\src\main\java\org\apache\roller\weblogger\ui\struts2\editor
Class - org.apache.roller.weblogger.ui.struts2.editor.MediaFileSearchBean  
Method - public void copyTo(org.apache.roller.weblogger.pojos.MediaFileFilter)  
Variable Criterion - order  
Block - B1
Exception - http://pastebin.com/tJDUPMPA

I tried it via UI also it is showing the same error

**Comment by tsantalis** [comment]
The bug has been replicated in release 5.0.60, but it has been already fixed in master.
Please wait for the next release or clone the master branch.
