### ISSUE TITLE
Try statement not added after refactoring Long Method

### ISSUE THREAD

**Issue by feroozkhanchintu** [tsantalis/JDeodorant#55]
Project : crawler4j (https://github.com/yasserg/crawler4j)
package : edu.uci.ics.crawler4j.fetcher
classname : PageFetchResult
Function : public boolean fetchContent(Page page)
variable consideration : page

When I perform LongMethod refactoring on the particular method, try catch statement is removed from the original method and exception is not added in the refactored method. So it is throwing compilation error while I'm using headless application. I could reproduce the same error in other files too if u need

**Comment by tsantalis** [comment]
The code to be extracted contains 3 statements as shown in the figure below

![before_refactoring](https://cloud.githubusercontent.com/assets/1483516/18592139/87a8ab8a-7c03-11e6-8811-93569e52c9a0.png)

After refactoring the code is shown in the figure below
![after_refactoring](https://cloud.githubusercontent.com/assets/1483516/18592169/aa6002b8-7c03-11e6-8dfb-c0c6be8fb886.png)

There is no compilation error; however, the statement `return true;`
inside the try block disappears after the refactoring,
and thus the refactoring does not preserve the behavior of the code.

I cannot replicate the compilation error, but there is a clear problem in the way the refactoring is performed.
