### ISSUE TITLE
Source code not compilable with Java 9

### ISSUE THREAD

**Issue by dmazinanian** [tsantalis/JDeodorant#62]
I gave JD a try on Java 9. In the first place, its source code can't be compiled, due to the compile errors happening because of the changes in the `javax.swing.tree` API.

Specifically, the methods in the `DefaultMutableTreeNode` used to return collections with raw types, now they return generic types with the type arguments being `TreeNode` (e.g., the methods `DefaultMutableTreeNode#breadthFirstEnumeration()` and `DefaultMutableTreeNode#children()` now return `Enumeration<TreeNode>` instead of `Enumeration`). The current implementation uses unsafe operations (e.g., in `gr.uom.java.ast.delegation.DelegationTree`)

**Comment by tsantalis** [comment]
JDeodorant is built with the Java version required by Eclipse
[Eclipse/Installation](https://wiki.eclipse.org/Eclipse/Installation)
Oxygen (4.7) and Neon (4.6) require Java 8.
Mars (4.5) and Luna (4.4) require Java 7.
Kepler (4.3) requires Java 6.
