### ISSUE TITLE
Error while duplicate code removal 

### ISSUE THREAD

**Issue by mkgungor** [tsantalis/JDeodorant#64]
When I try to do the same refactoring via watching this video 
https://www.youtube.com/watch?v=_WPtgG6JwJ8&t=601s

I faced the following Errors - could not proceed further.  Your help will be appreciated.

![image](https://user-images.githubusercontent.com/23154812/35077133-96b24d92-fbc9-11e7-82e5-4e49d0bf6057.png)

Details:
LineAndShapeRenderer.java
ScatterRenderer.java

Look at getLegendItem() method in both classes.

**Comment by tsantalis** [comment]
We have updated the preconditions to make them more strict.
In this particular example, there is a control dependence from statement
`if (isSeriesVisible(series) && isSeriesVisibleInLegend(series))`
to statements
`boolean lineVisible = getItemLineVisible(series, 0);`
`boolean shapeVisible = getItemShapeVisible(series, 0);`
that prevents moving these statements before the clone fragment
