### ISSUE TITLE
Application "eclipse.commandline.application" could not be found in the registry

### ISSUE THREAD

**Issue by jpantiuchina** [tsantalis/JDeodorant#65]
I followed the official [tutorial](http://users.encs.concordia.ca/%7Enikolaos/jdeodorant/index.php?option=com_content&view=article&id=87:how-can-i-execute-jdeodorant-in-headless-mode&catid=27:installation-questions&Itemid=41) on how to launch JDeodorant from command line, and on the last step I get the following error:
```
Application "eclipse.commandline.application" could not be found in the registry
```
I can run `eclipse.commandline.application` from Eclipse itself. This error only happens when I package the plugin in jar, put it into the plugins folder, and launch `eclipse` from command line.

My friend repeated the whole process (to make sure I didn’t missed anything), but got the same error. I am using Mac and the latest version of Eclipse. Tried putting the generated jar into both 
```
/Applications/Eclipse.app/Contents/Eclipse/plugins
```
and
```
~/.p2/pool/plugins
```
folders.

Do you know what might be the problem? I’ve read somewhere on a forum that Eclipse can silently ignore plugins if it doesn’t like them for some reason, and this might be what is happening here. Is there a way to investigate this? Tried adding the `-debug` switch, didn’t see anything about plugin loading.

**Comment by tsantalis** [comment]
Please try to use the [print-opportunities](https://github.com/tsantalis/jdeodorant-commandline/tree/print-opportunities) branch of the [jdeodorant-commandline](https://github.com/tsantalis/jdeodorant-commandline) project to run JDeodorant in headless mode. There is a very detailed [README](https://github.com/tsantalis/jdeodorant-commandline/blob/print-opportunities/README.md) that explains all necessary steps.

**Comment by jpantiuchina** [comment]
Thanks! Tried, but it seems that it's not what I need. Did I correctly understand that it needs as an input the output of a duplicate detection tool? 

I am looking for a way to run JDeodorant on a whole project (not just on duplicated code) and get the list of all smells/refactoring opportunities JDododorant can find. Like when I execute `Bad Smell | Feature Envy` in Eclipse.

**Comment by tsantalis** [comment]
The [print-opportunities](https://github.com/tsantalis/jdeodorant-commandline/tree/print-opportunities) branch offers the same functionality as the tutorial you followed from the website of JDeodorant, and additionally describes how to make an Eclipse product that can be executed independently from Eclipse. Please follow the first two sections of the [README](https://github.com/tsantalis/jdeodorant-commandline/blob/print-opportunities/README.md):
1. [Running the headless mode within Eclipse](https://github.com/tsantalis/jdeodorant-commandline#running-the-headless-mode-within-eclipse)
2. [Running as a standalone command-line application](https://github.com/tsantalis/jdeodorant-commandline#running-as-a-standalone-command-line-application)

and use the following command-line arguments:
> -p **projectName** (for example, jfreechart-1.0.10)
> -m **print_opportunities**

The project must be already open in the workspace

**Comment by jpantiuchina** [comment]
Yes, finally managed to do it! Thank you very much! :)
