### ISSUE TITLE
Problem in parsing cloneDR results folrder in Eclipse-JDeodorant-Plugin

### ISSUE THREAD

**Issue by Harpreet-ce-pbi** [tsantalis/JDeodorant#66]
I am working on JDeodorant to refactor duplicate code.
cloneDR tool has detected code clones in JHotDraw 7.0.6,
but while parsing cloneDr result folder a message is encountered every time "An error has occurred during parsing. An input file (s) may be corrupt.
![image](https://user-images.githubusercontent.com/47519192/52552360-e8fb2c80-2e05-11e9-9dcc-7cb82de5d9bc.png)

**Comment by tsantalis** [comment]
From what I see in the screenshot JHotDraw 7.0.6 project has compilation errors. Please fix these errors first and then try again.

**Comment by Harpreet-ce-pbi** [comment]
Dear sir
I have tried it on jedit 4.2 and jhotdraw 5.2.
In that error is encountered "source code for 366 instances is missing "
