### ISSUE TITLE
Duplicated code and project not compiling after refactoring Long Method.

### ISSUE THREAD

**Issue by rsain** [tsantalis/JDeodorant#70]
Project: Perseo-core ([https://github.com/telefonicaid/perseo-core](https://github.com/telefonicaid/perseo-core))
Commit: [19189b66cbb0ba97edad41147f749e3bb2d7d2fb](https://github.com/telefonicaid/perseo-core/commit/19189b66cbb0ba97edad41147f749e3bb2d7d2fb)
Package: src.main.java.org.json
Classname: [JSONObject](https://github.com/telefonicaid/perseo-core/blob/master/src/main/java/org/json/JSONObject.java)
Method: [private void populateMap(Object bean)](https://github.com/telefonicaid/perseo-core/blob/dba9bef47722bb8f0df88e56c9b3f7328e0f29d0/src/main/java/org/json/JSONObject.java#L983)
Operating system: Linux Debian
Eclipse version: 2019-03 (4.11.0)
JDeodorant plug-in version: 5.0.70 

When I perform Long Method refactoring from the JDeodorant Eclipse plug-in on the populateMap method, a block of code is duplicated in the extracted method. Because of this, a local variable is defined twice and the project contains compilation errors.

- Here the original code:

![image](https://user-images.githubusercontent.com/8953326/66486435-df1bed00-eaaa-11e9-90aa-7c6f82353d56.png)

- Here the refactored code (the wrongly duplicated code is highlighted in blue):

![image](https://user-images.githubusercontent.com/8953326/66487165-2eaee880-eaac-11e9-8577-931c98d7eb0a.png)

**Comment by tsantalis** [comment]
@rsain Out of all possible blocks to extract, which one did you select?
![2019-10-11 09_51_00-](https://user-images.githubusercontent.com/1483516/66656842-c3c8f300-ec0c-11e9-8454-6399b9a1c50b.png)

**Comment by tsantalis** [comment]
It seems only B2 block (0/20) creates the problem you reported. For all other blocks the code is refactored correctly.

**Comment by tsantalis** [comment]
Screenshot showing the refactored code after the fix
![2019-10-14 07_16_11-](https://user-images.githubusercontent.com/1483516/66747463-9c636780-ee52-11e9-87f8-ea26cb2f7837.png)

**Comment by rsain** [comment]
I still can replicate the issue when running JDeodorant over the entire project. However, when running JDeodorant over a single class (JSONObject) the refactoring is applied correctly.
