### ISSUE TITLE
Extracted method after refactoring Long Method throws an exception not thrown in the original code.

### ISSUE THREAD

**Issue by rsain** [tsantalis/JDeodorant#71]
Project: Perseo-core ([https://github.com/telefonicaid/perseo-core](https://github.com/telefonicaid/perseo-core))
Commit: [19189b66cbb0ba97edad41147f749e3bb2d7d2fb](https://github.com/telefonicaid/perseo-core/commit/19189b66cbb0ba97edad41147f749e3bb2d7d2fb)
Package: src.test.java.com.telefonica.iot.perseo
Classname: [TimeRulesStoreTest](https://github.com/telefonicaid/perseo-core/blob/master/src/test/java/com/telefonica/iot/perseo/TimeRulesStoreTest.java)
Method: [public void testCleanAllRules()](https://github.com/telefonicaid/perseo-core/blob/dba9bef47722bb8f0df88e56c9b3f7328e0f29d0/src/test/java/com/telefonica/iot/perseo/TimeRulesStoreTest.java#L154) 
Operating system: Linux Debian
Eclipse version: 2019-03 (4.11.0)
JDeodorant plug-in version: 5.0.70

When I perform Long Method refactoring from the JDeodorant Eclipse plug-in on the TimeRulesStoreTest method, a new exception (JSONException in this case) is thrown from the extracted method. This exception was not thrown in the original code and, therefore, the JSONException was not previously imported in the current class. This ends up with compilation errors in the project.

- Here the refactoring opportunity proposed by JDeodorant:

![image](https://user-images.githubusercontent.com/8953326/66489211-83a02e00-eaaf-11e9-8ffc-ccbc0ca8c90d.png)

- Here the refactored code (note the insertion of 'throws JSONException' in the extracted method):

![image](https://user-images.githubusercontent.com/8953326/66490255-2e651c00-eab1-11e9-9f44-3e2bde9ba1e8.png)

**Comment by tsantalis** [comment]
I am getting some compilation errors after building the project with `mvn eclipse:eclipse` related to
```java
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
```
in class `/perseo-core/src/test/java/com/telefonica/iot/perseo/UtilsTest.java`
@rsain What version of java you used to build the project?

**Comment by rsain** [comment]
I am using JavaSE-1.8 (java-8-oracle).

I hope it helps.

**Comment by tsantalis** [comment]
I excluded `/perseo-core/src/test/java/com/telefonica/iot/perseo/UtilsTest.java` from sources to replicate the bug.
All put calls throw `JSONException`
`body.put("name", ruleName);`
So, I think it's correct to add `throws` in the  signature of the extracted method.
The code should be updated to automatically add the missing import declaration statement.
