### ISSUE TITLE
Wrong access of field instance of the class itself in Extract Class refactoring

### ISSUE THREAD

**Issue by 123a6bcw** [tsantalis/JDeodorant#75]
Please consider this file
https://github.com/JetBrains-Research/IntelliJDeodorant/blob/god-class-apply-refactoring-merge/src/test/resources/testdata/ide/refactoring/godclass/TestChainedMethodAccess/initial/Test.java

Line 29 contains
`chained.b += 1;`

You can see the expected and actual results in the comment above.

**Comment by tsantalis** [comment]
Thanks @123a6bcw 
I am only getting one refactoring opportunity for Test.java, which includes the methods and fields highlighted in the screenshot below. Do you instantiate Extract Class Refactoring programmatically with random methods and fields?

![2020-01-14 21_00_10-](https://user-images.githubusercontent.com/1483516/72398504-2bfa0a00-3711-11ea-8747-6958e546cd94.png)
