### ISSUE TITLE
Extract Class refactoring does not support final initialization with a field or a static function call.

### ISSUE THREAD

**Issue by 123a6bcw** [tsantalis/JDeodorant#77]
In ExtractClassRefactoring::createExtractedTypeFieldReferenceInSourceClass()  
considered a possibility of a final field being initialized with either constructor parameter or a local variable. However, a final field can also be initialized with another final field, here's an example  
[initial class](https://github.com/JetBrains-Research/IntelliJDeodorant/tree/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithField/initial/Test.java)  
[expected source class](https://github.com/JetBrains-Research/IntelliJDeodorant/tree/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithField/expected/Test.java)  
[expected product class](https://github.com/JetBrains-Research/IntelliJDeodorant/tree/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithField/expected/TestProduct.java)

It is also possible to initialize a final field with a static function call.
[initial class](https://github.com/JetBrains-Research/IntelliJDeodorant/tree/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithStaticFunctionCall/initial/Test.java)  
[expected source class](https://github.com/JetBrains-Research/IntelliJDeodorant/tree/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithStaticFunctionCall/expected/Test.java)  
[expected product class](https://github.com/JetBrains-Research/IntelliJDeodorant/tree/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithStaticFunctionCall/expected/TestProduct.java)

JDeodorant will give error results in such cases (in both cases I used the first refactoring proposal).

**Comment by tsantalis** [comment]
Thanks @123a6bcw for the bug report.
I am getting 404 Page not found for all provided links.
Is it possible to update the links?

**Comment by 123a6bcw** [comment]
@tsantalis Sorry! Files were moved to master. I updated the links.
