### ISSUE TITLE
Unexpected exception in Extract Class refactoring with final fields

### ISSUE THREAD

**Issue by 123a6bcw** [tsantalis/JDeodorant#78]
Trying to use a first extract class proposal on this [source file](https://github.com/JetBrains-Research/IntelliJDeodorant/blob/master/src/test/resources/testdata/ide/refactoring/godclass/TestFinalInitialisationWithLocalVariable/initial/Test.java), Eclipse IDE gives me an unexpected exception. It has something to do with final fields `e` and `d`, if remove a final keyword from any of them, exception is no longer appears.

**Comment by tsantalis** [comment]
Same here. The link is giving 404 error

**Comment by 123a6bcw** [comment]
@tsantalis sorry, fixed.

**Comment by tsantalis** [comment]
This issue was caused because of overlapping DeleteEdits.
I introduced method `deleteOverlappingDeleteEdits()` to resolve this problem
