### ISSUE TITLE
Plug-in "ca.concordia.jdeodorant.eclipse.commandline-lambda" was unable to instantiate class "ca.concordia.jdeodorant.eclipse.commandline.Application".

### ISSUE THREAD

**Issue by asif33** [tsantalis/JDeodorant#79]
I followed the official [tutorial](https://github.com/tsantalis/jdeodorant-commandline) on how to launch JDeodorant as a stand alone command line application, and when I run `./eclipse -p projectname -m print_opportunities` I get the following error:

`Plug-in "ca.concordia.jdeodorant.eclipse.commandline-lambda" was unable to instantiate class "ca.concordia.jdeodorant.eclipse.commandline.Application".`

`Caused by: java.lang.ClassNotFoundException: gr.uom.java.ast.CompilationErrorDetectedException cannot be found by ca.concordia.jdeodorant.eclipse.commandline-lambda_1.0.0.202008251507`

I repeated the whole process using [this](https://github.com/tsantalis/jdeodorant-commandline/tree/print-opportunities) tutorial still getting the same error.

Do you know what might be the problem?

I am using macOS Catalina and latest version of Eclipse

**Comment by asif33** [comment]
The folder where I run the command `./eclipse -p projectname -m print_opportunities` creates a log file after showing the error mentioned above, I am pasting the log here for your kind perusal

`8/25/20, 3:13:33 PM EDT
 Eclipse Compiler for Java(TM) v20191203-2131, 3.20.0, Copyright IBM Corp 2000, 2015. All rights reserved.
----------
1. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/Application.java (at line 268)
	subtreesTest = new MatchingSubtreesTest(fileNamesTable.get(id),subTreeMatches.toString());
	                                                           ^^
Unlikely argument type int for get(Object) on a Map<String,String>
----------
2. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/Application.java (at line 335)
	List<CloneInfoWriter> infoWriters = new ArrayList<>();
	                                        ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
3. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/Application.java (at line 625)
	List<DivideAndConquerMatcher> mappers = new ArrayList<>();
	                                            ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
4. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/Application.java (at line 838)
	ArrayList<IMarker> result = new ArrayList<>();
	                                ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
5. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/ApplicationRunner.java (at line 117)
	} catch (NoSuchFieldException | SecurityException e) {
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Multi-catch parameters are not allowed for source level below 1.7
----------
6. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/ApplicationRunner.java (at line 263)
	Map<String, String> attributes = new HashMap<>();
	                                     ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
7. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/ApplicationRunner.java (at line 281)
	Map<String, String> attributes = new HashMap<>();
	                                     ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
8. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/ApplicationRunner.java (at line 291)
	Map<String, String> attributes = new HashMap<>();
	                                     ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
9. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/ApplicationRunner.java (at line 408)
	List<LineCoverage> lineCoverageList = new ArrayList<>();
	                                          ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
10. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cli/CLIParser.java (at line 331)
	List<String> toReturn = new ArrayList<>();
	                            ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
11. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 4)
	import gr.uom.java.ast.decomposition.cfg.mapping.PDGExpressionGap;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import gr.uom.java.ast.decomposition.cfg.mapping.PDGExpressionGap cannot be resolved
----------
12. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 5)
	import gr.uom.java.ast.decomposition.cfg.mapping.PDGNodeBlockGap;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import gr.uom.java.ast.decomposition.cfg.mapping.PDGNodeBlockGap cannot be resolved
----------
13. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 31)
	private final List<String> mainCSVLines = new ArrayList<>();
	                                              ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
14. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 32)
	private final List<String> mappersCSVLines = new ArrayList<>();
	                                                 ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
15. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 33)
	private final List<String> preconditionViolationsLines = new ArrayList<>();
	                                                             ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
16. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 34)
	private final List<String> compileErrorsLines = new ArrayList<>();
	                                                    ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
17. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 35)
	private final List<String> testReportDifferencesLines = new ArrayList<>();
	                                                            ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
18. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 36)
	private final List<String> expressionGapsInfoLines = new ArrayList<>();
	                                                         ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
19. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 37)
	private final List<String> blockGapsInfoLines = new ArrayList<>();
	                                                    ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
20. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 137)
	for (PDGNodeBlockGap pdgNodeBlockGap : mapperInfo.getMapper().getRefactorableBlockGaps()) {
	     ^^^^^^^^^^^^^^^
PDGNodeBlockGap cannot be resolved to a type
----------
21. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 137)
	for (PDGNodeBlockGap pdgNodeBlockGap : mapperInfo.getMapper().getRefactorableBlockGaps()) {
	                                                              ^^^^^^^^^^^^^^^^^^^^^^^^
The method getRefactorableBlockGaps() is undefined for the type DivideAndConquerMatcher
----------
22. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 152)
	for (PDGExpressionGap pdgExpressionGap : mapperInfo.getMapper().getRefactorableExpressionGaps()) {
	     ^^^^^^^^^^^^^^^^
PDGExpressionGap cannot be resolved to a type
----------
23. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoCSVWriter.java (at line 152)
	for (PDGExpressionGap pdgExpressionGap : mapperInfo.getMapper().getRefactorableExpressionGaps()) {
	                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method getRefactorableExpressionGaps() is undefined for the type DivideAndConquerMatcher
----------
----------
24. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/CloneInfoHTMLWriter.java (at line 111)
	List<CloneStructureNode> cloneMappingNodes = new ArrayList<>();
	                                                 ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
25. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/ClonePairInfo.java (at line 64)
	private List<PDGSubTreeMapperInfo> subtreeMappersList = new ArrayList<>();
	                                                            ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
26. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/ClonePairInfo.java (at line 69)
	private Set<String> testPackages = new HashSet<>();
	                                       ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
27. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/ClonePairInfo.java (at line 70)
	private Set<String> testSourceFolders = new HashSet<>();
	                                            ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
28. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/ClonePairInfo.java (at line 240)
	List<PDGSubTreeMapperInfo> toReturn = new ArrayList<>();
	                                          ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
29. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/ClonePairInfo.java (at line 272)
	this.subtreeMappersList = new ArrayList<>();
	                              ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
30. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/ClonePairInfo.java (at line 282)
	} catch (IllegalArgumentException  | JavaModelException e) {
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Multi-catch parameters are not allowed for source level below 1.7
----------
----------
31. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/PDGSubTreeMapperInfo.java (at line 16)
	private List<TestReportDifference> testResultsDifferences = new ArrayList<>();
	                                                                ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
32. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/cloneinfowriter/PDGSubTreeMapperInfo.java (at line 17)
	private Set<String> filesHavingCompileErrors = new HashSet<>();
	                                                   ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
33. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/coverage/TestReportResults.java (at line 47)
	private final Map<String, TestReport> testResults = new HashMap<>();
	                                                        ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
34. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/coverage/TestReportResults.java (at line 70)
	List<TestReportDifference> toReturn = new ArrayList<>();
	                                          ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
35. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 82)
	} catch (IOException | CoreException e) {
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Multi-catch parameters are not allowed for source level below 1.7
----------
36. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 93)
	List<LineCoverage> filteredLines = lineCoverageInfo
					.stream()
					.filter(row -> row.getPackageName().equals(packageNameDotsReplaced)
							&& row.getClassName().equals(className)
							&& row.getLine() >= startLine
							&& row.getLine() <= endLine)
					.collect(Collectors.toList());
	                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Type mismatch: cannot convert from List<Object> to List<LineCoverage>
----------
37. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 95)
	.filter(row -> row.getPackageName().equals(packageNameDotsReplaced)
							&& row.getClassName().equals(className)
							&& row.getLine() >= startLine
							&& row.getLine() <= endLine)
	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Lambda expressions are allowed only at source level 1.8 or above
----------
38. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 95)
	.filter(row -> row.getPackageName().equals(packageNameDotsReplaced)
	                                           ^^^^^^^^^^^^^^^^^^^^^^^
Cannot refer to the non-final local variable packageNameDotsReplaced defined in an enclosing scope
----------
39. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 96)
	&& row.getClassName().equals(className)
	                             ^^^^^^^^^
Cannot refer to the non-final local variable className defined in an enclosing scope
----------
40. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 97)
	&& row.getLine() >= startLine
	                    ^^^^^^^^^
Cannot refer to the non-final local variable startLine defined in an enclosing scope
----------
41. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 98)
	&& row.getLine() <= endLine)
	                    ^^^^^^^
Cannot refer to the non-final local variable endLine defined in an enclosing scope
----------
42. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 101)
	long coveredLinesCount = filteredLines.stream().filter(row->row.getStatus() != CoverageStatus.NOT_COVERED).count();
	                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Lambda expressions are allowed only at source level 1.8 or above
----------
43. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/parsers/CloneToolParser.java (at line 192)
	} catch (IOException | WriteException e) {
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Multi-catch parameters are not allowed for source level below 1.7
----------
----------
44. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/test/MatchingSubtreesTest.java (at line 10)
	import org.junit.Test;
	       ^^^^^^^^^^^^^^
The import org.junit.Test is never used
----------
45. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/test/MatchingSubtreesTest.java (at line 23)
	Scanner scanContent = new Scanner(content);
	        ^^^^^^^^^^^
Resource leak: 'scanContent' is never closed
----------
46. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/test/MatchingSubtreesTest.java (at line 24)
	Scanner scanObtainedMatch = new Scanner(obtainedMatch);
	        ^^^^^^^^^^^^^^^^^
Resource leak: 'scanObtainedMatch' is never closed
----------
----------
47. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/test/MatchingTest.java (at line 10)
	import org.junit.Test;
	       ^^^^^^^^^^^^^^
The import org.junit.Test is never used
----------
48. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/test/MatchingTest.java (at line 22)
	Scanner scanContent = new Scanner(content);
	        ^^^^^^^^^^^
Resource leak: 'scanContent' is never closed
----------
49. WARNING in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/test/MatchingTest.java (at line 23)
	Scanner scanObtainedMatch = new Scanner(obtainedMatch);
	        ^^^^^^^^^^^^^^^^^
Resource leak: 'scanObtainedMatch' is never closed
----------
----------
50. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/utility/FileLogger.java (at line 18)
	private static List<FileAppender<ILoggingEvent>> appenders = new ArrayList<>();
	                                                                 ^^^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
----------
51. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/utility/Mailer.java (at line 44)
	return new PasswordAuthentication(userName, password);
	                                  ^^^^^^^^
Cannot refer to the non-final local variable userName defined in an enclosing scope
----------
52. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/utility/Mailer.java (at line 44)
	return new PasswordAuthentication(userName, password);
	                                            ^^^^^^^^
Cannot refer to the non-final local variable password defined in an enclosing scope
----------
----------
53. ERROR in /Users/asif.imran/Desktop/commandline/jdeodorant-commandline/src/ca/concordia/jdeodorant/eclipse/commandline/utility/SourceDirectoryUtility.java (at line 23)
	Set<String> allSrcDirectories = new TreeSet<>(new Comparator<String>() {
	                                    ^^^^^^^
'<>' operator is not allowed for source level below 1.7
----------
53 problems (46 errors, 7 warnings)
`

**Comment by asif33** [comment]
Another log file shows the following message

`8/25/20, 3:13:33 PM EDT
Eclipse Compiler for Java(TM) v20191203-2131, 3.20.0, Copyright IBM Corp 2000, 2015. All rights reserved.
option -bootclasspath not supported at compliance level 9 and above`

**Comment by tsantalis** [comment]
It seems that you are not using a JDK compiler.
Please check in Preferences -> Java -> Installed JREs that you have a JDK 8 or newer

![2020-08-27 07_17_41-Preferences](https://user-images.githubusercontent.com/1483516/91436192-9fcacc00-e835-11ea-96ee-d789a883ec1c.png)

and check in the Java Build Path of the JDeodorant-Commandline project that you have JavaSE-1.8 or newer as a JRE System Library.

![2020-08-27 07_21_30-Properties for JDeodorant-Commandline](https://user-images.githubusercontent.com/1483516/91436471-313a3e00-e836-11ea-9f63-e68892486319.png)

**Comment by asif33** [comment]
I have checked your suggested solution and have ensured that JDK compiler is selected as seen below 
![image](https://user-images.githubusercontent.com/1041846/91461661-41aee080-e857-11ea-98ea-5371a3ac0d60.png)

 and also went to Build Path of jdeodorant-commandline project to make sure I have JavaSE-1.8
<img width="1346" alt="Screen Shot 2020-08-27 at 11 21 45 AM" src="https://user-images.githubusercontent.com/1041846/91461864-8470b880-e857-11ea-8c0c-84d6e8909cf4.png">

Still I am facing the error as shown below:-

![image](https://user-images.githubusercontent.com/1041846/91461907-92bed480-e857-11ea-80fe-894d0295c09a.png)

**Comment by asif33** [comment]
I have managed to solve the errors after a series of troubleshooting. The code parses, however I am getting a null pointer exception. I am executing the following command 

`./eclipse -p "project/name/in/workspace"  -m PARSE -t CLONE_TOOL_DECKARD -x out.xls`

<img width="975" alt="Screen Shot 2020-08-27 at 5 21 08 PM" src="https://user-images.githubusercontent.com/1041846/91496201-b4d14a80-e889-11ea-9bcd-ae96371c9f11.png">

I believe I am not giving all arguments correctly, can you guide me in this regard?

**Comment by tsantalis** [comment]
You need to specify with the `-i` argument the file where you stored the clone detection results of Deckard on project cpuhog

**Comment by asif33** [comment]
Thank you very much. Since I have not used Deckard before, I decided to obtain the clone detection results for Apacke-Ant-1.7.0 project from [Assessing the Refactorability of Software Clones](https://users.encs.concordia.ca/~nikolaos/TSE_2015/). I believe the output of clone detection should be one of the following found in .7z file under [Deckard](https://users.encs.concordia.ca/~nikolaos/TSE_2015/results/apache-ant-1.7.0-deckard.7z) but please correct me if I am wrong

apache-ant-1.7.0-deckard.xls

So I took that file in my directory where the eclipse product was created, also imported the project source code apache-ant-1.7.0 into the workspace and executed the following command:-

`./eclipse -p "apache-ant-1.7.0" -m PARSE -i apache-ant-1.7.0-deckard.xls -x output.xls -m PARSE --tool CLONE_TOOL_DECKARD`

where output.xls is a file which I created in the directory of the eclipse product to store the parsed results. However I am still getting the error as follows:

<img width="1368" alt="Screen Shot 2020-08-27 at 11 40 17 PM" src="https://user-images.githubusercontent.com/1041846/91518615-acdfcd80-e8be-11ea-9e33-b3b6a90c88cc.png">

If you think there is an issue with my approach please kindly suggest the solve, I can take it forward from there

**Comment by tsantalis** [comment]
`-i` full path to file `clusters/post_cluster_vdb_50_0_allg_0.95_50`
This is the result file of Deckard
