### ISSUE TITLE
Stackoverflow error when running JDeodorant on OpenMap 

### ISSUE THREAD

**Issue by jaslatendresse** [tsantalis/JDeodorant#80]
Whenever I run JDeodorant on [OpenMap](https://github.com/OpenMap-java/openmap), I get the following error: 

<img width="407" alt="Capture d’écran, le 2020-09-25 à 12 00 20" src="https://user-images.githubusercontent.com/17911957/94294313-a2e8d300-ff2d-11ea-9a3a-72e6360e7360.png">

that is for any code smell detection. 

**IDE**: Eclipse JEE-2020-09

**Commit**: 9532b118358cb28d0cc022cc29cc4109485bfd22

**Steps to the error**: 

1. Select God Class from code smell tab
2. Select OpenMap project from the project explorer
3. Click on the find code smells button from JDeodorant div 

This error is also obtained with any other code smell by reproducing the steps mentioned above.

**Comment by tsantalis** [comment]
@jaslatendresse How did you build the project? Does it have compilation errors when you run the code smell detection?

**Comment by tsantalis** [comment]
> java.lang.StackOverflowError
> 	at gr.uom.java.ast.TypeObject.equals(TypeObject.java:85)
> 	at gr.uom.java.ast.AbstractMethodInvocationObject.equals(AbstractMethodInvocationObject.java:100)
> 	at java.util.HashMap.getNode(HashMap.java:572)
> 	at java.util.LinkedHashMap.get(LinkedHashMap.java:440)
> 	at gr.uom.java.ast.SystemObject.containsDelegate(SystemObject.java:140)
> 	at gr.uom.java.distance.MyAbstractExpression.recurseDelegations(MyAbstractExpression.java:81)
> 	at gr.uom.java.distance.MyAbstractExpression.recurseDelegations(MyAbstractExpression.java:82)

**Comment by tsantalis** [comment]
Wow, they have a function that calls itself ! The definition of infinite recursion
```java
public boolean isPlotable(double lat, double lon) {
    return isPlotable(lat, lon);
}
```
