### ISSUE TITLE
JDeodorant added to ProductHunt

### ISSUE THREAD

**Issue by slim16165** [tsantalis/JDeodorant#85]
I apologize for using this channel to contact you. I'm passionate about code refactoring and I've found your tool after a lot of research. It's a very interesting tool but it's not well advertised, I've invested some minutes to list it into one of the most famous directories, hope this helps. 
https://www.producthunt.com/posts/jdeodorant

**Comment by tsantalis** [comment]
Hi @slim16165 
Thank you for advertising JDeodorant.
The project was active between 2007-2019, but is no longer maintained, as our current research focuses on refactoring mining.
You might find interesting the [RefactoringMiner](https://github.com/tsantalis/RefactoringMiner) project.
