### ISSUE TITLE
JDeodorant used for Java1.8

### ISSUE THREAD

**Issue by Coppelian** [tsantalis/JDeodorant#86]
Hi author,

I faced a problem in refactoring projects using JDeodorant.
I wanted to test JDeodorant on Java1.8 projects. I installed JDeodorant using Eclipse marketplace with version 2024-06R.
However, it is limited to Java11 and causes internal errors. The dataset I used was defects4j v2.
For many projects, it reports with blank after inspection.

I tried older Eclipse versions with marketplace installation; it was successfully installed but cannot be used.

I tried to download jar files from http://users.encs.concordia.ca/~nikolaos/update/
But I'm confused about which version I should use for this task.

Can you help me with this issue? Thank you.

**Comment by tsantalis** [comment]
@Coppelian 
Can you please copy the internal errors being reported.
Go to the error logs and copy the stack-trace.

Normally, there should not be a problem.
I think the reason behind the problems you are facing is that JDeodorant is only working on successfully compiled projects.
If you just try to run it on Java files, which are not part of an Eclipse project (built without compilation errors), then it will not work, regardless of the version you are using.

**Comment by Coppelian** [comment]
@tsantalis Thank you for the response. You're correct, those projects are not properly set up with ant build.xml, leading to failure compilation.
I had a problem using the JDeodorant Commandline tool. 
https://github.com/tsantalis/jdeodorant-commandline/issues/18
Can you help me take a look into this issue? Thank you.
